
export type Outfit = {
  id: number;
  gender: 'male' | 'female';
  context: 'work/office' | 'casual' | 'party/date' | 'sport/active';
  style: 'basic' | 'streetwear' | 'elegant' | 'sporty';
  season: 'spring' | 'summer' | 'autumn' | 'winter';
  color: 'black' | 'white' | 'pastel' | 'earth-tone' | 'vibrant';
  images: string[];
  description: string;
  longDescription: string;
  aiHint: string;
  items: { name: string; type: string }[];
  shoppingLinks: { store: string; url: string }[];
};

export const outfits: Outfit[] = [
  { 
    id: 1, 
    gender: 'female', 
    context: 'work/office', 
    style: 'elegant', 
    season: 'autumn', 
    color: 'earth-tone', 
    images: ['https://images.unsplash.com/photo-1542327534-59a1fe8ea5eb?w=400&h=500&fit=crop', 'https://images.unsplash.com/photo-1542327534-59a1fe8ea5eb?w=500&h=400&fit=crop'],
    description: 'Phong cách công sở mùa thu sang trọng',
    longDescription: 'Một bộ trang phục thanh lịch và chuyên nghiệp, hoàn hảo cho mùa thu trong môi trường công sở. Bảng màu đất toát lên vẻ tinh tế và ấm áp, phù hợp cho các cuộc họp quan trọng hoặc trang phục công sở hàng ngày.',
    aiHint: 'woman office fashion',
    items: [
      { name: 'Áo khoác trench màu be', type: 'Áo khoác' },
      { name: 'Áo blouse lụa trắng', type: 'Áo' },
      { name: 'Quần kẻ sọc màu nâu', type: 'Quần' },
      { name: 'Bốt da cổ ngắn', type: 'Giày' },
      { name: 'Túi tote', type: 'Phụ kiện' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 2, 
    gender: 'female', 
    context: 'casual', 
    style: 'basic', 
    season: 'spring', 
    color: 'pastel', 
    images: ['https://images.unsplash.com/photo-1551803091-e2ab652d5636?w=400&h=500&fit=crop'],
    description: 'Trang phục dạo phố mùa xuân',
    longDescription: 'Một bộ trang phục thoải mái và tươi mới, lý tưởng cho một ngày dạo phố vào mùa xuân. Các màu pastel mang lại cảm giác nhẹ nhàng và thoáng đãng, hoàn hảo cho một cuộc dạo chơi trong công viên hoặc một buổi hẹn cà phê.',
    aiHint: 'woman casual fashion',
    items: [
      { name: 'Áo len hồng nhạt', type: 'Áo' },
      { name: 'Quần jean màu sáng', type: 'Quần' },
      { name: 'Giày sneaker trắng', type: 'Giày' },
      { name: 'Túi tote vải', type: 'Phụ kiện' },
    ],
    shoppingLinks: [
      { store: 'Lazada', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 3, 
    gender: 'female', 
    context: 'party/date', 
    style: 'elegant', 
    season: 'summer', 
    color: 'black', 
    images: ['https://images.unsplash.com/photo-1581044777550-4cfa6ce24862?w=400&h=500&fit=crop'],
    description: 'Đêm hè thanh lịch',
    longDescription: 'Một chiếc váy đen lộng lẫy và tinh tế cho một sự kiện buổi tối mùa hè hoặc một buổi hẹn hò lãng mạn. Vẻ đẹp thanh lịch vượt thời gian của nó đảm bảo bạn sẽ tạo nên một tuyên bố.',
    aiHint: 'woman party dress',
    items: [
      { name: 'Váy bodycon đen', type: 'Váy' },
      { name: 'Giày cao gót quai mảnh', type: 'Giày' },
      { name: 'Túi clutch', type: 'Phụ kiện' },
      { name: 'Bông tai mạ vàng', type: 'Phụ kiện' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Shopee', url: '#' },
    ],
  },
  { 
    id: 4, 
    gender: 'female', 
    context: 'sport/active', 
    style: 'sporty', 
    season: 'summer', 
    color: 'vibrant', 
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=500&fit=crop'],
    description: 'Đồ thể thao mùa hè rực rỡ',
    longDescription: 'Một bộ đồ thể thao tươi sáng và năng động cho các buổi tập luyện mùa hè của bạn. Màu sắc rực rỡ sẽ giúp bạn có động lực, trong khi chất liệu vải giúp bạn mát mẻ.',
    aiHint: 'woman sportswear',
    items: [
      { name: 'Áo bra thể thao neon', type: 'Áo' },
      { name: 'Quần legging cạp cao', type: 'Quần' },
      { name: 'Giày chạy bộ', type: 'Giày' },
    ],
    shoppingLinks: [
        { store: 'Lazada', url: '#' },
    ],
  },
  { 
    id: 5, 
    gender: 'male', 
    context: 'work/office', 
    style: 'basic', 
    season: 'winter', 
    color: 'black', 
    images: ['https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&h=500&fit=crop'],
    description: 'Công sở mùa đông hiện đại',
    longDescription: 'Một bộ trang phục sắc sảo và hiện đại cho văn phòng vào mùa đông. Vẻ ngoài nhiều lớp vừa phong cách vừa thiết thực để giữ ấm.',
    aiHint: 'man office fashion',
    items: [
      { name: 'Áo cổ lọ đen', type: 'Áo' },
      { name: 'Áo khoác len xám', type: 'Áo khoác' },
      { name: 'Quần tây màu than', type: 'Quần' },
      { name: 'Bốt Chelsea da', type: 'Giày' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 6, 
    gender: 'male', 
    context: 'casual', 
    style: 'streetwear', 
    season: 'autumn', 
    color: 'earth-tone', 
    images: ['https://images.unsplash.com/photo-1539149398648-395213b38035?w=400&h=500&fit=crop'],
    description: 'Phong cách streetwear mùa thu',
    aiHint: 'man streetwear',
    longDescription: 'Một phong cách streetwear mát mẻ và giản dị cho mùa thu. Các tông màu đất và các món đồ nhiều lớp là hoàn hảo cho thời tiết thay đổi.',
    items: [
      { name: 'Áo hoodie oversized', type: 'Áo' },
      { name: 'Quần cargo', type: 'Quần' },
      { name: 'Giày sneaker cao cổ', type: 'Giày' },
      { name: 'Mũ beanie', type: 'Phụ kiện' },
    ],
    shoppingLinks: [
      { store: 'Shopee', url: '#' },
    ],
  },
  { 
    id: 7, 
    gender: 'male', 
    context: 'party/date', 
    style: 'elegant', 
    season: 'spring', 
    color: 'white', 
    images: ['https://images.unsplash.com/photo-1617127365659-3c74b9d1c750?w=400&h=500&fit=crop'],
    description: 'Hẹn hò mùa xuân sắc sảo',
    longDescription: 'Một bộ trang phục sắc sảo và thanh lịch cho một buổi hẹn hò mùa xuân. Màu sắc tươi sáng hoàn hảo cho một vẻ ngoài buổi tối trong lành.',
    aiHint: 'man elegant suit',
    items: [
      { name: 'Áo sơ mi linen trắng', type: 'Áo' },
      { name: 'Quần chinos màu navy', type: 'Quần' },
      { name: 'Giày lười màu nâu', type: 'Giày' },
      { name: 'Thắt lưng da', type: 'Phụ kiện' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 8, 
    gender: 'male', 
    context: 'sport/active', 
    style: 'sporty', 
    season: 'summer', 
    color: 'vibrant', 
    images: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=500&fit=crop'],
    description: 'Trang phục năng động mùa hè',
    longDescription: 'Trang phục năng động, tiện dụng và phong cách cho các môn thể thao mùa hè. Chất liệu vải thoáng khí và màu sắc rực rỡ sẽ giúp bạn tiếp tục.',
    aiHint: 'man sportswear',
    items: [
      { name: 'Áo thun thấm mồ hôi', type: 'Áo' },
      { name: 'Quần short thể thao', type: 'Quần' },
      { name: 'Giày tập luyện đa năng', type: 'Giày' },
    ],
    shoppingLinks: [
      { store: 'Lazada', url: '#' },
    ],
  },
  { 
    id: 9, 
    gender: 'female', 
    context: 'casual', 
    style: 'streetwear', 
    season: 'winter', 
    color: 'black', 
    images: ['https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=400&h=500&fit=crop'],
    description: 'Phong cách đường phố mùa đông',
    longDescription: 'Một phong cách streetwear sắc sảo và ấm áp cho mùa đông. Bộ trang phục toàn màu đen vừa sang trọng vừa thiết thực cho cái lạnh.',
    aiHint: 'woman streetwear',
    items: [
      { name: 'Áo khoác phao đen', type: 'Áo khoác' },
      { name: 'Áo hoodie đen', type: 'Áo' },
      { name: 'Quần jean skinny đen', type: 'Quần' },
      { name: 'Bốt chiến binh', type: 'Giày' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Shopee', url: '#' },
    ],
  },
  { 
    id: 10, 
    gender: 'male', 
    context: 'casual', 
    style: 'basic', 
    season: 'summer', 
    color: 'white', 
    images: ['https://images.unsplash.com/photo-1506152982424-a0a4c251886c?w=400&h=500&fit=crop'],
    description: 'Trang phục thường ngày mùa hè cổ điển',
    longDescription: 'Một bộ trang phục thường ngày vượt thời gian và đơn giản cho mùa hè. Sự kết hợp giữa áo phông trắng và quần jean thật dễ dàng.',
    aiHint: 'man summer casual',
    items: [
      { name: 'Áo thun cổ tròn trắng', type: 'Áo' },
      { name: 'Quần short denim', type: 'Quần' },
      { name: 'Giày espadrilles vải', type: 'Giày' },
      { name: 'Kính râm', type: 'Phụ kiện' },
    ],
    shoppingLinks: [
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 11, 
    gender: 'female', 
    context: 'work/office', 
    style: 'basic', 
    season: 'spring', 
    color: 'white', 
    images: ['https://images.unsplash.com/photo-1609505848912-252936335118?w=400&h=500&fit=crop'],
    description: 'Công sở mùa xuân tối giản',
    longDescription: 'Một bộ trang phục gọn gàng và tối giản cho văn phòng vào mùa xuân. Bảng màu đơn giản tạo ra một vẻ ngoài bóng bẩy và chuyên nghiệp.',
    aiHint: 'woman minimalist office',
    items: [
      { name: 'Áo blazer trắng', type: 'Áo khoác' },
      { name: 'Áo hai dây trắng', type: 'Áo' },
      { name: 'Quần tây màu be', type: 'Quần' },
      { name: 'Giày cao gót màu nude', type: 'Giày' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
    ],
  },
  { 
    id: 12, 
    gender: 'male', 
    context: 'party/date', 
    style: 'streetwear', 
    season: 'autumn', 
    color: 'vibrant', 
    images: ['https://images.unsplash.com/photo-1513028349275-520415311828?w=400&h=500&fit=crop'],
    description: 'Tiệc tùng mùa thu nhiều lớp',
    longDescription: 'Một bộ trang phục streetwear nhiều lớp hoàn hảo cho một bữa tiệc mùa thu. Chiếc áo khoác rực rỡ tạo thêm điểm nhấn màu sắc cho vẻ ngoài.',
    aiHint: 'man party streetwear',
    items: [
      { name: 'Áo khoác bomber rực rỡ', type: 'Áo khoác' },
      { name: 'Áo phông in hình', type: 'Áo' },
      { name: 'Quần jean rách', type: 'Quần' },
      { name: 'Bốt da lộn', type: 'Giày' },
    ],
    shoppingLinks: [
      { store: 'Shopee', url: '#' },
    ],
  },
];
