export type Outfit = {
  id: number;
  gender: 'male' | 'female';
  context: 'work/office' | 'casual' | 'party/date' | 'sport/active';
  style: 'basic' | 'streetwear' | 'elegant' | 'sporty';
  season: 'spring' | 'summer' | 'autumn' | 'winter';
  color: 'black' | 'white' | 'pastel' | 'earth-tone' | 'vibrant';
  images: string[];
  description: string;
  longDescription: string;
  aiHint: string;
  items: { name: string; type: string }[];
  shoppingLinks: { store: string; url: string }[];
};

export const outfits: Outfit[] = [
  { 
    id: 1, 
    gender: 'female', 
    context: 'work/office', 
    style: 'elegant', 
    season: 'autumn', 
    color: 'earth-tone', 
    images: ['https://images.unsplash.com/photo-1542327534-59a1fe8ea5eb?w=400&h=500&fit=crop', 'https://images.unsplash.com/photo-1542327534-59a1fe8ea5eb?w=500&h=400&fit=crop'],
    description: 'Chic Autumn Office Look',
    longDescription: 'An elegant and professional outfit perfect for the autumn season in a corporate environment. The earth-tone color palette exudes sophistication and warmth, suitable for important meetings or daily office wear.',
    aiHint: 'woman office fashion',
    items: [
      { name: 'Beige Trench Coat', type: 'Outerwear' },
      { name: 'White Silk Blouse', type: 'Top' },
      { name: 'Brown Plaid Trousers', type: 'Bottom' },
      { name: 'Leather Ankle Boots', type: 'Shoes' },
      { name: 'Structured Tote Bag', type: 'Accessory' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 2, 
    gender: 'female', 
    context: 'casual', 
    style: 'basic', 
    season: 'spring', 
    color: 'pastel', 
    images: ['https://images.unsplash.com/photo-1551803091-e2ab652d5636?w=400&h=500&fit=crop'],
    description: 'Spring Casual Day Out',
    longDescription: 'A comfortable and fresh outfit ideal for a casual day out in spring. The pastel colors bring a light and airy feel, perfect for a walk in the park or a coffee date.',
    aiHint: 'woman casual fashion',
    items: [
      { name: 'Light Pink Sweater', type: 'Top' },
      { name: 'Light Wash Jeans', type: 'Bottom' },
      { name: 'White Sneakers', type: 'Shoes' },
      { name: 'Canvas Tote Bag', type: 'Accessory' },
    ],
    shoppingLinks: [
      { store: 'Lazada', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 3, 
    gender: 'female', 
    context: 'party/date', 
    style: 'elegant', 
    season: 'summer', 
    color: 'black', 
    images: ['https://images.unsplash.com/photo-1581044777550-4cfa6ce24862?w=400&h=500&fit=crop'],
    description: 'Elegant Summer Night',
    longDescription: 'A stunning and sophisticated black dress for a summer evening event or a romantic date. Its timeless elegance ensures you will make a statement.',
    aiHint: 'woman party dress',
    items: [
      { name: 'Black Bodycon Dress', type: 'Dress' },
      { name: 'Strappy Heels', type: 'Shoes' },
      { name: 'Clutch Bag', type: 'Accessory' },
      { name: 'Gold-plated earrings', type: 'Accessory' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Shopee', url: '#' },
    ],
  },
  { 
    id: 4, 
    gender: 'female', 
    context: 'sport/active', 
    style: 'sporty', 
    season: 'summer', 
    color: 'vibrant', 
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=500&fit=crop'],
    description: 'Vibrant Summer Sportswear',
    longDescription: 'A bright and energetic sportswear set for your summer workouts. The vibrant colors will keep you motivated, while the fabric keeps you cool.',
    aiHint: 'woman sportswear',
    items: [
      { name: 'Neon Sports Bra', type: 'Top' },
      { name: 'High-waist Leggings', type: 'Bottom' },
      { name: 'Running Shoes', type: 'Shoes' },
    ],
    shoppingLinks: [
        { store: 'Lazada', url: '#' },
    ],
  },
  { 
    id: 5, 
    gender: 'male', 
    context: 'work/office', 
    style: 'basic', 
    season: 'winter', 
    color: 'black', 
    images: ['https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&h=500&fit=crop'],
    description: 'Modern Winter Office',
    longDescription: 'A sharp and modern outfit for the office during winter. The layered look is both stylish and practical for staying warm.',
    aiHint: 'man office fashion',
    items: [
      { name: 'Black Turtleneck', type: 'Top' },
      { name: 'Grey Wool Coat', type: 'Outerwear' },
      { name: 'Charcoal Trousers', type: 'Bottom' },
      { name: 'Leather Chelsea Boots', type: 'Shoes' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 6, 
    gender: 'male', 
    context: 'casual', 
    style: 'streetwear', 
    season: 'autumn', 
    color: 'earth-tone', 
    images: ['https://images.unsplash.com/photo-1539149398648-395213b38035?w=400&h=500&fit=crop'],
    description: 'Autumn Streetwear Vibe',
    aiHint: 'man streetwear',
    longDescription: 'A cool and casual streetwear look for autumn. The earth tones and layered pieces are perfect for the changing weather.',
    items: [
      { name: 'Oversized Hoodie', type: 'Top' },
      { name: 'Cargo Pants', type: 'Bottom' },
      { name: 'High-top Sneakers', type: 'Shoes' },
      { name: 'Beanie', type: 'Accessory' },
    ],
    shoppingLinks: [
      { store: 'Shopee', url: '#' },
    ],
  },
  { 
    id: 7, 
    gender: 'male', 
    context: 'party/date', 
    style: 'elegant', 
    season: 'spring', 
    color: 'white', 
    images: ['https://images.unsplash.com/photo-1617127365659-3c74b9d1c750?w=400&h=500&fit=crop'],
    description: 'Sharp Spring Date Night',
    longDescription: 'A crisp and elegant outfit for a spring date night. The light colors are perfect for a fresh evening look.',
    aiHint: 'man elegant suit',
    items: [
      { name: 'White Linen Shirt', type: 'Top' },
      { name: 'Navy Chinos', type: 'Bottom' },
      { name: 'Brown Loafers', type: 'Shoes' },
      { name: 'Leather Belt', type: 'Accessory' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 8, 
    gender: 'male', 
    context: 'sport/active', 
    style: 'sporty', 
    season: 'summer', 
    color: 'vibrant', 
    images: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=500&fit=crop'],
    description: 'Summer Active Gear',
    longDescription: 'Functional and stylish activewear for summer sports. The breathable fabric and vibrant color will keep you going.',
    aiHint: 'man sportswear',
    items: [
      { name: 'Moisture-wicking T-shirt', type: 'Top' },
      { name: 'Athletic Shorts', type: 'Bottom' },
      { name: 'Cross-training Shoes', type: 'Shoes' },
    ],
    shoppingLinks: [
      { store: 'Lazada', url: '#' },
    ],
  },
  { 
    id: 9, 
    gender: 'female', 
    context: 'casual', 
    style: 'streetwear', 
    season: 'winter', 
    color: 'black', 
    images: ['https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=400&h=500&fit=crop'],
    description: 'Winter Street Style',
    longDescription: 'An edgy and warm streetwear look for winter. The all-black ensemble is both chic and practical for the cold.',
    aiHint: 'woman streetwear',
    items: [
      { name: 'Black Puffer Jacket', type: 'Outerwear' },
      { name: 'Black Hoodie', type: 'Top' },
      { name: 'Black Skinny Jeans', type: 'Bottom' },
      { name: 'Combat Boots', type: 'Shoes' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
      { store: 'Shopee', url: '#' },
    ],
  },
  { 
    id: 10, 
    gender: 'male', 
    context: 'casual', 
    style: 'basic', 
    season: 'summer', 
    color: 'white', 
    images: ['https://images.unsplash.com/photo-1506152982424-a0a4c251886c?w=400&h=500&fit=crop'],
    description: 'Classic Summer Casual',
    longDescription: 'A timeless and simple casual outfit for summer. The white t-shirt and jeans combo is effortlessly cool.',
    aiHint: 'man summer casual',
    items: [
      { name: 'White Crew-neck T-shirt', type: 'Top' },
      { name: 'Denim Shorts', type: 'Bottom' },
      { name: 'Canvas Espadrilles', type: 'Shoes' },
      { name: 'Sunglasses', type: 'Accessory' },
    ],
    shoppingLinks: [
      { store: 'Uniqlo', url: '#' },
    ],
  },
  { 
    id: 11, 
    gender: 'female', 
    context: 'work/office', 
    style: 'basic', 
    season: 'spring', 
    color: 'white', 
    images: ['https://images.unsplash.com/photo-1609505848912-252936335118?w=400&h=500&fit=crop'],
    description: 'Minimalist Spring Office',
    longDescription: 'A clean and minimalist outfit for the office in spring. The simple color palette creates a polished and professional look.',
    aiHint: 'woman minimalist office',
    items: [
      { name: 'White Blazer', type: 'Outerwear' },
      { name: 'White Camisole', type: 'Top' },
      { name: 'Beige Trousers', type: 'Bottom' },
      { name: 'Nude Heels', type: 'Shoes' },
    ],
    shoppingLinks: [
      { store: 'Zara', url: '#' },
    ],
  },
  { 
    id: 12, 
    gender: 'male', 
    context: 'party/date', 
    style: 'streetwear', 
    season: 'autumn', 
    color: 'vibrant', 
    images: ['https://images.unsplash.com/photo-1513028349275-520415311828?w=400&h=500&fit=crop'],
    description: 'Autumn Party Layers',
    longDescription: 'A layered streetwear outfit that is perfect for an autumn party. The vibrant jacket adds a pop of color to the look.',
    aiHint: 'man party streetwear',
    items: [
      { name: 'Vibrant Bomber Jacket', type: 'Outerwear' },
      { name: 'Graphic T-shirt', type: 'Top' },
      { name: 'Distressed Jeans', type: 'Bottom' },
      { name: 'Suede Boots', type: 'Shoes' },
    ],
    shoppingLinks: [
      { store: 'Shopee', url: '#' },
    ],
  },
];
