
export type Outfit = {
  id: number;
  gender: 'male' | 'female';
  context: 'work/office' | 'casual' | 'party/date' | 'sport/active' | 'tet' | 'game-anime';
  style: 'basic' | 'streetwear' | 'elegant' | 'sporty';
  season: 'spring' | 'summer' | 'autumn' | 'winter';
  color: 'black' | 'white' | 'pastel' | 'earth-tone' | 'vibrant';
  mainImage: string;
  imageSourceText?: string;
  imageSourceUrl?: string;
  description: string;
  longDescription: string;
  aiHint: string;
  items: {
    name: string;
    type: string;
    imageUrl: string;
    shoppingLinks: { store: string; url: string }[];
  }[];
};

export const outfits: Outfit[] = [
  {
    id: 1,
    gender: 'male',
    context: 'work/office',
    style: 'elegant',
    season: 'autumn',
    color: 'earth-tone',
    mainImage: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=800&q=80',
    imageSourceText: 'Unsplash',
    imageSourceUrl: 'https://unsplash.com/photos/man-wearing-black-suit-jacket-1503341455253-b2e723bb3dbb',
    description: 'Bộ suit nam thanh lịch cho môi trường công sở.',
    longDescription:
      'Trang phục công sở nam với bộ suit màu earth-tone, áo sơ mi trắng, cà vạt tối màu và giày da. Phù hợp cho mùa thu và các buổi họp quan trọng.',
    aiHint: 'Suggest formal office outfits for men in autumn with earth-tone colors.',
    items: [
      {
        name: 'Áo vest earth-tone',
        type: 'top',
        imageUrl: 'https://images.unsplash.com/photo-1520975918318-3f6c8cbdc79e?auto=format&fit=crop&w=400&q=80',
        shoppingLinks: [
          { store: 'Zara', url: 'https://www.zara.com/' },
          { store: 'Uniqlo', url: 'https://www.uniqlo.com/' },
        ],
      },
      {
        name: 'Áo sơ mi trắng',
        type: 'top',
        imageUrl: 'https://images.unsplash.com/photo-1520975434759-16c0d3c0ee2c?auto=format&fit=crop&w=400&q=80',
        shoppingLinks: [{ store: 'H&M', url: 'https://www.hm.com/' }],
      },
      {
        name: 'Quần tây đồng bộ',
        type: 'bottom',
        imageUrl: 'https://images.unsplash.com/photo-1516822003754-cca485356ecb?auto=format&fit=crop&w=400&q=80',
        shoppingLinks: [{ store: 'Topman', url: 'https://www.topman.com/' }],
      },
      {
        name: 'Giày da đen',
        type: 'shoes',
        imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=400&q=80',
        shoppingLinks: [{ store: 'Clarks', url: 'https://www.clarks.com/' }],
      },
    ],
  },
  {
    id: 2,
    gender: 'female',
    context: 'casual',
    style: 'streetwear',
    season: 'summer',
    color: 'pastel',
    mainImage: 'https://picsum.photos/seed/outfit-2-main/400/500',
    imageSourceText: 'Placeholder',
    imageSourceUrl: 'https://picsum.photos',
    description: 'Trang phục streetwear nữ pastel cho mùa hè.',
    longDescription:
      'Bộ outfit gồm áo phông oversize pastel kết hợp với quần short jean năng động, giày sneaker trắng và phụ kiện trẻ trung. Phù hợp cho dạo phố hoặc đi chơi cùng bạn bè.',
    aiHint: 'Suggest pastel casual summer outfits with oversized tee and shorts.',
    items: [
      {
        name: 'Áo phông pastel',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-2-item-1/200/200',
        shoppingLinks: [
          { store: 'Zara', url: 'https://www.zara.com/' },
          { store: 'H&M', url: 'https://www.hm.com/' },
        ],
      },
      {
        name: 'Quần short jean',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-2-item-2/200/200',
        shoppingLinks: [{ store: 'Levis', url: 'https://www.levi.com/' }],
      },
      {
        name: 'Giày sneaker trắng',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-2-item-3/200/200',
        shoppingLinks: [
          { store: 'Nike', url: 'https://www.nike.com/' },
          { store: 'Adidas', url: 'https://www.adidas.com/' },
        ],
      },
      {
        name: 'Túi đeo chéo nhỏ',
        type: 'accessory',
        imageUrl: 'https://picsum.photos/seed/outfit-2-item-4/200/200',
        shoppingLinks: [{ store: 'Charles & Keith', url: 'https://www.charleskeith.com/' }],
      },
    ],
  },
  {
    id: 3,
    gender: 'male',
    context: 'tet',
    style: 'basic',
    season: 'summer',
    color: 'vibrant',
    mainImage: 'https://picsum.photos/seed/outfit-3-main/400/500',
    description: 'Outfit nam đơn giản nhưng nổi bật cho buổi hẹn hò.',
    longDescription:
      'Áo sơ mi ngắn tay màu sắc tươi sáng kết hợp quần kaki sáng màu và giày lười. Thêm phụ kiện đồng hồ để tạo điểm nhấn lịch lãm.',
    aiHint: 'Suggest vibrant men outfits for summer date nights.',
    items: [
      {
        name: 'Áo sơ mi ngắn tay',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-3-item-1/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần kaki sáng màu',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-3-item-2/200/200',
        shoppingLinks: [{ store: 'Dockers', url: 'https://www.dockers.com/' }],
      },
      {
        name: 'Giày lười da nâu',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-3-item-3/200/200',
        shoppingLinks: [{ store: 'Aldo', url: 'https://www.aldoshoes.com/' }],
      },
    ],
  },
  {
    id: 4,
    gender: 'female',
    context: 'tet',
    style: 'elegant',
    season: 'spring',
    color: 'pastel',
    mainImage: 'https://picsum.photos/seed/outfit-4-main/400/500',
    description: 'Váy pastel nữ tính cho buổi hẹn mùa xuân.',
    longDescription:
      'Chiếc váy midi pastel nhẹ nhàng kết hợp giày cao gót nude và túi xách nhỏ xinh. Phù hợp với buổi hẹn hò hoặc tiệc thân mật.',
    aiHint: 'Suggest elegant pastel dresses for spring parties or dates.',
    items: [
      {
        name: 'Váy midi pastel',
        type: 'dress',
        imageUrl: 'https://picsum.photos/seed/outfit-4-item-1/200/200',
        shoppingLinks: [{ store: 'Mango', url: 'https://shop.mango.com/' }],
      },
      {
        name: 'Giày cao gót nude',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-4-item-2/200/200',
        shoppingLinks: [{ store: 'Nine West', url: 'https://www.ninewest.com/' }],
      },
      {
        name: 'Túi xách nhỏ',
        type: 'accessory',
        imageUrl: 'https://picsum.photos/seed/outfit-4-item-3/200/200',
        shoppingLinks: [{ store: 'Michael Kors', url: 'https://www.michaelkors.com/' }],
      },
    ],
  },
  {
    id: 5,
    gender: 'male',
    context: 'game-anime',
    style: 'sporty',
    season: 'summer',
    color: 'black',
    mainImage: 'https://picsum.photos/seed/outfit-5-main/400/500',
    description: 'Đồ tập gym nam mạnh mẽ và năng động.',
    longDescription:
      'Áo tank top đen, quần short thể thao và giày chạy bộ thoáng khí. Thích hợp cho luyện tập mùa hè.',
    aiHint: 'Suggest black sporty men outfits for gym in summer.',
    items: [
      {
        name: 'Áo tank top đen',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-5-item-1/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
      {
        name: 'Quần short thể thao',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-5-item-2/200/200',
        shoppingLinks: [{ store: 'Adidas', url: 'https://www.adidas.com/' }],
      },
      {
        name: 'Giày chạy bộ',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-5-item-3/200/200',
        shoppingLinks: [{ store: 'Asics', url: 'https://www.asics.com/' }],
      },
    ],
  },
  {
    id: 6,
    gender: 'female',
    context: 'work/office',
    style: 'basic',
    season: 'winter',
    color: 'black',
    mainImage: 'https://picsum.photos/seed/outfit-6-main/400/500',
    description: 'Trang phục công sở nữ mùa đông cơ bản.',
    longDescription:
      'Áo len cổ lọ đen kết hợp quần tây, áo blazer xám và ankle boots. Giữ ấm và vẫn thanh lịch cho môi trường công sở.',
    aiHint: 'Suggest basic black office outfits for women in winter.',
    items: [
      {
        name: 'Áo len cổ lọ đen',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-6-item-1/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần tây đen',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-6-item-2/200/200',
        shoppingLinks: [{ store: 'Zara', url: 'https://www.zara.com/' }],
      },
      {
        name: 'Áo blazer xám',
        type: 'outerwear',
        imageUrl: 'https://picsum.photos/seed/outfit-6-item-3/200/200',
        shoppingLinks: [{ store: 'Mango', url: 'https://shop.mango.com/' }],
      },
      {
        name: 'Ankle boots',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-6-item-4/200/200',
        shoppingLinks: [{ store: 'Aldo', url: 'https://www.aldoshoes.com/' }],
      },
    ],
  },
  {
    id: 7,
    gender: 'male',
    context: 'game-anime',
    style: 'streetwear',
    season: 'spring',
    color: 'earth-tone',
    mainImage: 'https://picsum.photos/seed/outfit-7-main/400/500',
    description: 'Streetwear nam xuân đơn giản nhưng cá tính.',
    longDescription:
      'Áo hoodie màu nâu nhạt, quần jogger và sneaker trắng. Thêm mũ lưỡi trai để tạo phong cách năng động.',
    aiHint: 'Suggest spring earth-tone casual streetwear outfits for men.',
    items: [
      {
        name: 'Áo hoodie nâu',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-7-item-1/200/200',
        shoppingLinks: [{ store: 'H&M', url: 'https://www.hm.com/' }],
      },
      {
        name: 'Quần jogger',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-7-item-2/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
      {
        name: 'Sneaker trắng',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-7-item-3/200/200',
        shoppingLinks: [{ store: 'Adidas', url: 'https://www.adidas.com/' }],
      },
    ],
  },
  {
    id: 8,
    gender: 'female',
    context: 'sport/active',
    style: 'sporty',
    season: 'autumn',
    color: 'vibrant',
    mainImage: 'https://picsum.photos/seed/outfit-8-main/400/500',
    description: 'Đồ yoga nữ với màu sắc tươi sáng.',
    longDescription:
      'Áo bra thể thao neon, quần legging co giãn và giày training. Thích hợp cho yoga hoặc tập fitness vào mùa thu.',
    aiHint: 'Suggest vibrant autumn sporty yoga outfits for women.',
    items: [
      {
        name: 'Áo bra neon',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-8-item-1/200/200',
        shoppingLinks: [{ store: 'Lululemon', url: 'https://shop.lululemon.com/' }],
      },
      {
        name: 'Quần legging',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-8-item-2/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
      {
        name: 'Giày training',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-8-item-3/200/200',
        shoppingLinks: [{ store: 'Reebok', url: 'https://www.reebok.com/' }],
      },
    ],
  },
  {
    id: 9,
    gender: 'male',
    context: 'work/office',
    style: 'basic',
    season: 'summer',
    color: 'white',
    mainImage: 'https://picsum.photos/seed/outfit-9-main/400/500',
    description: 'Công sở mùa hè thoáng mát với áo sơ mi trắng.',
    longDescription:
      'Áo sơ mi trắng linen, quần tây xám sáng và giày da lười. Giữ sự thoải mái và vẫn chuyên nghiệp.',
    aiHint: 'Suggest basic white office outfits for men in summer.',
    items: [
      {
        name: 'Áo sơ mi linen trắng',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-9-item-1/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần tây xám',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-9-item-2/200/200',
        shoppingLinks: [{ store: 'Topman', url: 'https://www.topman.com/' }],
      },
      {
        name: 'Giày lười nâu',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-9-item-3/200/200',
        shoppingLinks: [{ store: 'Clarks', url: 'https://www.clarks.com/' }],
      },
    ],
  },
  {
    id: 10,
    gender: 'female',
    context: 'party/date',
    style: 'elegant',
    season: 'winter',
    color: 'black',
    mainImage: 'https://picsum.photos/seed/outfit-10-main/400/500',
    description: 'Đầm đen thanh lịch cho buổi tiệc mùa đông.',
    longDescription:
      'Chiếc đầm đen bodycon kết hợp với áo khoác lông, giày cao gót đen và clutch. Phong cách sang trọng cho mùa đông.',
    aiHint: 'Suggest elegant black winter party dresses for women.',
    items: [
      {
        name: 'Đầm bodycon đen',
        type: 'dress',
        imageUrl: 'https://picsum.photos/seed/outfit-10-item-1/200/200',
        shoppingLinks: [{ store: 'Zara', url: 'https://www.zara.com/' }],
      },
      {
        name: 'Áo khoác lông',
        type: 'outerwear',
        imageUrl: 'https://picsum.photos/seed/outfit-10-item-2/200/200',
        shoppingLinks: [{ store: 'Mango', url: 'https://shop.mango.com/' }],
      },
      {
        name: 'Giày cao gót đen',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-10-item-3/200/200',
        shoppingLinks: [{ store: 'Aldo', url: 'https://www.aldoshoes.com/' }],
      },
      {
        name: 'Clutch đen',
        type: 'accessory',
        imageUrl: 'https://picsum.photos/seed/outfit-10-item-4/200/200',
        shoppingLinks: [{ store: 'Michael Kors', url: 'https://www.michaelkors.com/' }],
      },
    ],
  }, {
    id: 11,
    gender: 'male',
    context: 'tet',
    style: 'streetwear',
    season: 'spring',
    color: 'vibrant',
    mainImage: 'https://picsum.photos/seed/outfit-11-main/400/500',
    imageSourceText: 'Placeholder',
    imageSourceUrl: 'https://picsum.photos',
    description: 'Outfit streetwear nam với áo hoodie sáng màu và quần jogger.',
    longDescription:
      'Áo hoodie màu vibrant kết hợp với quần jogger thoải mái và sneaker chunky. Phù hợp cho phong cách đường phố năng động mùa xuân.',
    aiHint: 'Suggest vibrant spring streetwear outfits with hoodie and joggers.',
    items: [
      {
        name: 'Áo hoodie sáng màu',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-11-item-1/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
      {
        name: 'Quần jogger đen',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-11-item-2/200/200',
        shoppingLinks: [{ store: 'Adidas', url: 'https://www.adidas.com/' }],
      },
      {
        name: 'Sneaker chunky',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-11-item-3/200/200',
        shoppingLinks: [{ store: 'Puma', url: 'https://www.puma.com/' }],
      },
    ],
  },
  {
    id: 12,
    gender: 'female',
    context: 'party/date',
    style: 'elegant',
    season: 'summer',
    color: 'black',
    mainImage: 'https://picsum.photos/seed/outfit-12-main/400/500',
    imageSourceText: 'Placeholder',
    imageSourceUrl: 'https://picsum.photos',
    description: 'Đầm đen sang trọng cho buổi hẹn hò hoặc tiệc tối.',
    longDescription:
      'Chiếc đầm đen ôm body với chất liệu satin kết hợp cùng giày cao gót và clutch. Mang lại vẻ đẹp quyến rũ, sang trọng trong buổi hẹn hò mùa hè.',
    aiHint: 'Suggest elegant black dresses for date night in summer.',
    items: [
      {
        name: 'Đầm đen satin',
        type: 'dress',
        imageUrl: 'https://picsum.photos/seed/outfit-12-item-1/200/200',
        shoppingLinks: [{ store: 'Zara', url: 'https://www.zara.com/' }],
      },
      {
        name: 'Giày cao gót',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-12-item-2/200/200',
        shoppingLinks: [{ store: 'Aldo', url: 'https://www.aldoshoes.com/' }],
      },
      {
        name: 'Clutch ánh kim',
        type: 'accessory',
        imageUrl: 'https://picsum.photos/seed/outfit-12-item-3/200/200',
        shoppingLinks: [{ store: 'Charles & Keith', url: 'https://www.charleskeith.com/' }],
      },
    ],
  },
  {
    id: 13,
    gender: 'male',
    context: 'sport/active',
    style: 'sporty',
    season: 'summer',
    color: 'white',
    mainImage: 'https://picsum.photos/seed/outfit-13-main/400/500',
    description: 'Trang phục thể thao nam trắng đơn giản, thoải mái.',
    longDescription:
      'Áo thun thể thao màu trắng thoáng khí kết hợp với quần short chạy bộ và giày chạy nhẹ. Phù hợp cho tập gym hoặc chạy bộ ngoài trời.',
    aiHint: 'Suggest sporty white outfits for men in summer.',
    items: [
      {
        name: 'Áo thun thể thao trắng',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-13-item-1/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
      {
        name: 'Quần short chạy bộ',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-13-item-2/200/200',
        shoppingLinks: [{ store: 'Adidas', url: 'https://www.adidas.com/' }],
      },
      {
        name: 'Giày chạy',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-13-item-3/200/200',
        shoppingLinks: [{ store: 'Asics', url: 'https://www.asics.com/' }],
      },
    ],
  },
  {
    id: 14,
    gender: 'female',
    context: 'work/office',
    style: 'basic',
    season: 'spring',
    color: 'pastel',
    mainImage: 'https://picsum.photos/seed/outfit-14-main/400/500',
    description: 'Áo sơ mi pastel kết hợp quần culottes công sở nữ.',
    longDescription:
      'Trang phục công sở nữ với áo sơ mi pastel và quần culottes thoải mái, kết hợp giày loafer và túi tote. Mang lại cảm giác trẻ trung, thanh lịch.',
    aiHint: 'Suggest pastel office outfits for women in spring.',
    items: [
      {
        name: 'Áo sơ mi pastel',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-14-item-1/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần culottes',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-14-item-2/200/200',
        shoppingLinks: [{ store: 'Mango', url: 'https://shop.mango.com/' }],
      },
      {
        name: 'Giày loafer',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-14-item-3/200/200',
        shoppingLinks: [{ store: 'H&M', url: 'https://www.hm.com/' }],
      },
      {
        name: 'Túi tote',
        type: 'accessory',
        imageUrl: 'https://picsum.photos/seed/outfit-14-item-4/200/200',
        shoppingLinks: [{ store: 'Charles & Keith', url: 'https://www.charleskeith.com/' }],
      },
    ],
  },
  {
    id: 15,
    gender: 'male',
    context: 'party/date',
    style: 'elegant',
    season: 'winter',
    color: 'black',
    mainImage: 'https://picsum.photos/seed/outfit-15-main/400/500',
    description: 'Áo khoác dạ đen lịch lãm cho buổi hẹn mùa đông.',
    longDescription:
      'Áo khoác dạ đen dài, kết hợp áo cổ lọ và quần tây, cùng giày Chelsea boots. Tạo vẻ ngoài ấm áp nhưng vẫn phong cách cho buổi hẹn tối mùa đông.',
    aiHint: 'Suggest elegant winter date outfits for men in black tones.',
    items: [
      {
        name: 'Áo khoác dạ đen',
        type: 'outerwear',
        imageUrl: 'https://picsum.photos/seed/outfit-15-item-1/200/200',
        shoppingLinks: [{ store: 'Zara', url: 'https://www.zara.com/' }],
      },
      {
        name: 'Áo cổ lọ',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-15-item-2/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần tây',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-15-item-3/200/200',
        shoppingLinks: [{ store: 'Topman', url: 'https://www.topman.com/' }],
      },
      {
        name: 'Chelsea boots',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-15-item-4/200/200',
        shoppingLinks: [{ store: 'Clarks', url: 'https://www.clarks.com/' }],
      },
    ],
  },
  {
    id: 16,
    gender: 'female',
    context: 'sport/active',
    style: 'sporty',
    season: 'autumn',
    color: 'earth-tone',
    mainImage: 'https://picsum.photos/seed/outfit-16-main/400/500',
    description: 'Set đồ yoga earth-tone cho nữ.',
    longDescription:
      'Bộ đồ tập yoga gồm áo bra và quần legging earth-tone, kết hợp áo khoác nhẹ và giày sneaker. Phù hợp cho mùa thu khi tập luyện hoặc đi dạo.',
    aiHint: 'Suggest sporty earth-tone yoga outfits for women in autumn.',
    items: [
      {
        name: 'Áo bra thể thao',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-16-item-1/200/200',
        shoppingLinks: [{ store: 'Lululemon', url: 'https://shop.lululemon.com/' }],
      },
      {
        name: 'Quần legging earth-tone',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-16-item-2/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
      {
        name: 'Áo khoác nhẹ',
        type: 'outerwear',
        imageUrl: 'https://picsum.photos/seed/outfit-16-item-3/200/200',
        shoppingLinks: [{ store: 'Adidas', url: 'https://www.adidas.com/' }],
      },
      {
        name: 'Sneaker',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-16-item-4/200/200',
        shoppingLinks: [{ store: 'Reebok', url: 'https://www.reebok.com/' }],
      },
    ],
  },
  {
    id: 17,
    gender: 'male',
    context: 'casual',
    style: 'basic',
    season: 'summer',
    color: 'white',
    mainImage: 'https://picsum.photos/seed/outfit-17-main/400/500',
    description: 'Outfit basic nam mùa hè với áo thun trắng và quần jean.',
    longDescription:
      'Áo thun trắng đơn giản kết hợp quần jean xanh và sneaker trắng. Phong cách cơ bản nhưng không lỗi thời, phù hợp mọi hoàn cảnh thường ngày.',
    aiHint: 'Suggest simple casual summer outfits with white t-shirt and jeans.',
    items: [
      {
        name: 'Áo thun trắng',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-17-item-1/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần jean xanh',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-17-item-2/200/200',
        shoppingLinks: [{ store: 'Levis', url: 'https://www.levi.com/' }],
      },
      {
        name: 'Sneaker trắng',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-17-item-3/200/200',
        shoppingLinks: [{ store: 'Nike', url: 'https://www.nike.com/' }],
      },
    ],
  },
  {
    id: 18,
    gender: 'female',
    context: 'tet',
    style: 'streetwear',
    season: 'spring',
    color: 'vibrant',
    mainImage: 'https://picsum.photos/seed/outfit-18-main/400/500',
    description: 'Set streetwear nữ nổi bật với crop top và chân váy ngắn.',
    longDescription:
      'Crop top rực rỡ kết hợp chân váy ngắn và giày sneaker platform. Mang lại sự năng động, cá tính cho các buổi tiệc ngoài trời mùa xuân.',
    aiHint: 'Suggest vibrant streetwear outfits for women in spring.',
    items: [
      {
        name: 'Crop top rực rỡ',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-18-item-1/200/200',
        shoppingLinks: [{ store: 'Bershka', url: 'https://www.bershka.com/' }],
      },
      {
        name: 'Chân váy ngắn',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-18-item-2/200/200',
        shoppingLinks: [{ store: 'Pull&Bear', url: 'https://www.pullandbear.com/' }],
      },
      {
        name: 'Sneaker platform',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-18-item-3/200/200',
        shoppingLinks: [{ store: 'Fila', url: 'https://www.fila.com/' }],
      },
    ],
  },
  {
    id: 19,
    gender: 'male',
    context: 'work/office',
    style: 'basic',
    season: 'winter',
    color: 'earth-tone',
    mainImage: 'https://picsum.photos/seed/outfit-19-main/400/500',
    description: 'Áo len earth-tone kết hợp sơ mi công sở nam mùa đông.',
    longDescription:
      'Áo len cổ tròn earth-tone mặc ngoài áo sơ mi trắng, đi kèm quần tây và giày oxford. Mang lại sự thanh lịch, chuyên nghiệp nhưng vẫn ấm áp.',
    aiHint: 'Suggest office outfits for men in earth-tone during winter.',
    items: [
      {
        name: 'Áo len earth-tone',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-19-item-1/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Áo sơ mi trắng',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-19-item-2/200/200',
        shoppingLinks: [{ store: 'H&M', url: 'https://www.hm.com/' }],
      },
      {
        name: 'Quần tây xám',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-19-item-3/200/200',
        shoppingLinks: [{ store: 'Topman', url: 'https://www.topman.com/' }],
      },
      {
        name: 'Giày oxford',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-19-item-4/200/200',
        shoppingLinks: [{ store: 'Clarks', url: 'https://www.clarks.com/' }],
      },
    ],
  },
  {
    id: 20,
    gender: 'female',
    context: 'casual',
    style: 'basic',
    season: 'autumn',
    color: 'pastel',
    mainImage: 'https://picsum.photos/seed/outfit-20-main/400/500',
    description: 'Áo cardigan pastel cho nữ mùa thu.',
    longDescription:
      'Cardigan pastel kết hợp áo thun trắng, quần jean skinny và sneaker. Tạo phong cách thoải mái, trẻ trung cho mùa thu se lạnh.',
    aiHint: 'Suggest pastel casual outfits for women in autumn.',
    items: [
      {
        name: 'Cardigan pastel',
        type: 'outerwear',
        imageUrl: 'https://picsum.photos/seed/outfit-20-item-1/200/200',
        shoppingLinks: [{ store: 'Zara', url: 'https://www.zara.com/' }],
      },
      {
        name: 'Áo thun trắng',
        type: 'top',
        imageUrl: 'https://picsum.photos/seed/outfit-20-item-2/200/200',
        shoppingLinks: [{ store: 'Uniqlo', url: 'https://www.uniqlo.com/' }],
      },
      {
        name: 'Quần jean skinny',
        type: 'bottom',
        imageUrl: 'https://picsum.photos/seed/outfit-20-item-3/200/200',
        shoppingLinks: [{ store: 'Levis', url: 'https://www.levi.com/' }],
      },
      {
        name: 'Sneaker trắng',
        type: 'shoes',
        imageUrl: 'https://picsum.photos/seed/outfit-20-item-4/200/200',
        shoppingLinks: [{ store: 'Adidas', url: 'https://www.adidas.com/' }],
      },
    ],
  },
  
];


// export const outfits: Outfit[] = [
//   {
//     id: 1,
//     gender: 'female',
//     context: 'work/office',
//     style: 'elegant',
//     season: 'autumn',
//     color: 'earth-tone',
//     mainImage: 'https://images.unsplash.com/photo-1621619856624-42fd193a0661?w=1080&q=80',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/a-woman-in-a-plaid-skirt-and-white-blouse-is-walking-down-the-street-59a1fe8ea5eb',
//     description: 'Phong cách công sở mùa thu sang trọng',
//     longDescription: 'Thanh lịch và chuyên nghiệp, hoàn hảo cho môi trường công sở mùa thu.',
//     aiHint: 'woman office fashion',
//     items: [
//       { name: 'Áo khoác trench màu be', type: 'Áo khoác', imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80', shoppingLinks: [{ store: 'Zara', url: '#' }] },
//       { name: 'Áo blouse lụa trắng', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1642615835477-d303d7dc9ee9?w=1080&q=80', shoppingLinks: [{ store: 'Uniqlo', url: '#' }] },
//       { name: 'Quần kẻ sọc màu nâu', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80', shoppingLinks: [] },
//       { name: 'Bốt da cổ ngắn', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1635151227785-429f420c6b9d?w=1080&q=80', shoppingLinks: [{ store: 'Shopee', url: '#' }] },
//       { name: 'Túi tote', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=800&q=80', shoppingLinks: [{ store: 'Lazada', url: '#' }] },
//     ],
//   },
//   {
//     id: 2,
//     gender: 'female',
//     context: 'casual',
//     style: 'basic',
//     season: 'spring',
//     color: 'pastel',
//     mainImage: 'https://images.unsplash.com/photo-1551803091-e2ab652d5636?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-wearing-pink-sweater-and-distressed-blue-jeans-e2ab652d5636',
//     description: 'Trang phục dạo phố mùa xuân',
//     longDescription: 'Thoải mái và tươi mới, lý tưởng cho một ngày dạo phố mùa xuân.',
//     aiHint: 'woman casual fashion',
//     items: [
//       { name: 'Áo len hồng nhạt', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1551803091-e2ab652d5636?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }] },
//       { name: 'Quần jean màu sáng', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Uniqlo', url: '#' }] },
//       { name: 'Giày sneaker trắng', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Túi tote vải', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1544893236-5e26f8c5b3de?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 3,
//     gender: 'female',
//     context: 'party/date',
//     style: 'elegant',
//     season: 'summer',
//     color: 'black',
//     mainImage: 'https://images.unsplash.com/photo-1581044777550-4cfa6ce24862?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-in-black-spaghetti-strap-dress-4cfa6ce24862',
//     description: 'Đêm hè thanh lịch',
//     longDescription: 'Lộng lẫy và tinh tế cho một sự kiện buổi tối hoặc một buổi hẹn hò.',
//     aiHint: 'woman party dress',
//     items: [
//       { name: 'Váy bodycon đen', type: 'Váy', imageUrl: 'https://images.unsplash.com/photo-1581044777550-4cfa6ce24862?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Zara', url: '#' }, { store: 'Shopee', url: '#' }] },
//       { name: 'Giày cao gót quai mảnh', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1590099033615-be195f8d575c?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Túi clutch', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1566150905458-1bf1f2997d0d?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Bông tai mạ vàng', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1615591373009-6612a83327b4?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 4,
//     gender: 'female',
//     context: 'sport/active',
//     style: 'sporty',
//     season: 'summer',
//     color: 'vibrant',
//     mainImage: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-in-black-sports-bra-and-black-leggings-doing-exercise-d25dfeac3438',
//     description: 'Đồ thể thao mùa hè rực rỡ',
//     longDescription: 'Tươi sáng và năng động cho các buổi tập luyện mùa hè.',
//     aiHint: 'woman sportswear',
//     items: [
//       { name: 'Áo bra thể thao neon', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1584735935639-5fb37a233418?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }] },
//       { name: 'Quần legging cạp cao', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }] },
//       { name: 'Giày chạy bộ', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 5,
//     gender: 'male',
//     context: 'work/office',
//     style: 'basic',
//     season: 'winter',
//     color: 'black',
//     mainImage: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/man-in-black-turtleneck-sweater-and-gray-blazer-1ab2a1c593e8',
//     description: 'Công sở mùa đông hiện đại',
//     longDescription: 'Sắc sảo và hiện đại, vừa phong cách vừa thiết thực để giữ ấm.',
//     aiHint: 'man office fashion',
//     items: [
//       { name: 'Áo cổ lọ đen', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1615112662283-328682348a6a?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Uniqlo', url: '#' }] },
//       { name: 'Áo khoác len xám', type: 'Áo khoác', imageUrl: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Zara', url: '#' }] },
//       { name: 'Quần tây màu than', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1542327534-59a1fe8ea5eb?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Bốt Chelsea da', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1603845939999-bdd97093ca5e?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 6,
//     gender: 'male',
//     context: 'casual',
//     style: 'streetwear',
//     season: 'autumn',
//     color: 'earth-tone',
//     mainImage: 'https://images.unsplash.com/photo-1539149398648-395213b38035?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/man-in-brown-hoodie-and-black-pants-standing-on-road-during-daytime-395213b38035',
//     description: 'Phong cách streetwear mùa thu',
//     aiHint: 'man streetwear',
//     longDescription: 'Mát mẻ và giản dị cho mùa thu, hoàn hảo cho thời tiết thay đổi.',
//     items: [
//       { name: 'Áo hoodie oversized', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1539149398648-395213b38035?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Shopee', url: '#' }] },
//       { name: 'Quần cargo', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1611252391039-30424a68c743?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Giày sneaker cao cổ', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1673070a5?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Mũ beanie', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Shopee', url: '#' }] },
//     ],
//   },
//   {
//     id: 7,
//     gender: 'male',
//     context: 'party/date',
//     style: 'elegant',
//     season: 'spring',
//     color: 'white',
//     mainImage: 'https://images.unsplash.com/photo-1617127365659-3c74b9d1c750?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/a-man-in-a-white-shirt-and-blue-pants-3c74b9d1c750',
//     description: 'Hẹn hò mùa xuân sắc sảo',
//     longDescription: 'Sắc sảo và thanh lịch, hoàn hảo cho một vẻ ngoài buổi tối trong lành.',
//     aiHint: 'man elegant suit',
//     items: [
//       { name: 'Áo sơ mi linen trắng', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1617127365659-3c74b9d1c750?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Uniqlo', url: '#' }] },
//       { name: 'Quần chinos màu navy', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Zara', url: '#' }] },
//       { name: 'Giày lười màu nâu', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1603845939999-bdd97093ca5e?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Thắt lưng da', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1614749323746-957262526323?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 8,
//     gender: 'male',
//     context: 'sport/active',
//     style: 'sporty',
//     season: 'summer',
//     color: 'vibrant',
//     mainImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/man-in-black-tank-top-and-black-shorts-using-barbell-6078c6bfb5c5',
//     description: 'Trang phục năng động mùa hè',
//     longDescription: 'Năng động, tiện dụng và phong cách cho các môn thể thao mùa hè.',
//     aiHint: 'man sportswear',
//     items: [
//       { name: 'Áo thun thấm mồ hôi', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }] },
//       { name: 'Quần short thể thao', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1594498652135-373435b3448a?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }] },
//       { name: 'Giày tập luyện đa năng', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1595861203623-234bd31145a3?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 9,
//     gender: 'female',
//     context: 'casual',
//     style: 'streetwear',
//     season: 'winter',
//     color: 'black',
//     mainImage: 'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-in-black-jacket-and-black-pants-standing-on-snow-covered-ground-during-daytime-a2d80e2277fc',
//     description: 'Phong cách đường phố mùa đông',
//     longDescription: 'Sắc sảo và ấm áp, vừa sang trọng vừa thiết thực cho cái lạnh.',
//     aiHint: 'woman streetwear',
//     items: [
//       { name: 'Áo khoác phao đen', type: 'Áo khoác', imageUrl: 'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Zara', url: '#' }] },
//       { name: 'Áo hoodie đen', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1616613670987-a267f7615951?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Shopee', url: '#' }] },
//       { name: 'Quần jean skinny đen', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1541094649733-a3b1f307528b?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Bốt chiến binh', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 10,
//     gender: 'male',
//     context: 'casual',
//     style: 'basic',
//     season: 'summer',
//     color: 'white',
//     mainImage: 'https://images.unsplash.com/photo-1506152982424-a0a4c251886c?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/man-wearing-white-crew-neck-t-shirt-and-blue-denim-shorts-a0a4c251886c',
//     description: 'Trang phục thường ngày mùa hè cổ điển',
//     longDescription: 'Vượt thời gian và đơn giản, một sự kết hợp dễ dàng cho mùa hè.',
//     aiHint: 'man summer casual',
//     items: [
//       { name: 'Áo thun cổ tròn trắng', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1506152982424-a0a4c251886c?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Uniqlo', url: '#' }] },
//       { name: 'Quần short denim', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1603344287447-1f4a9a4e6c64?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Giày espadrilles vải', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1603142289453-7313a778c434?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Kính râm', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 11,
//     gender: 'female',
//     context: 'work/office',
//     style: 'basic',
//     season: 'spring',
//     color: 'white',
//     mainImage: 'https://images.unsplash.com/photo-1609505848912-252936335118?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-in-white-blazer-and-white-pants-252936335118',
//     description: 'Công sở mùa xuân tối giản',
//     longDescription: 'Gọn gàng và tối giản, tạo ra một vẻ ngoài bóng bẩy và chuyên nghiệp.',
//     aiHint: 'woman minimalist office',
//     items: [
//       { name: 'Áo blazer trắng', type: 'Áo khoác', imageUrl: 'https://images.unsplash.com/photo-1609505848912-252936335118?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Zara', url: '#' }] },
//       { name: 'Áo hai dây trắng', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1574279633945-8456a9a35e0a?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Quần tây màu be', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Giày cao gót màu nude', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1590099033615-be195f8d575c?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 12,
//     gender: 'male',
//     context: 'party/date',
//     style: 'streetwear',
//     season: 'autumn',
//     color: 'vibrant',
//     mainImage: 'https://images.unsplash.com/photo-1513028349275-520415311828?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/man-in-red-and-black-jacket-and-blue-jeans-520415311828',
//     description: 'Tiệc tùng mùa thu nhiều lớp',
//     longDescription: 'Nhiều lớp và rực rỡ, hoàn hảo cho một bữa tiệc mùa thu.',
//     aiHint: 'man party streetwear',
//     items: [
//       { name: 'Áo khoác bomber rực rỡ', type: 'Áo khoác', imageUrl: 'https://images.unsplash.com/photo-1513028349275-520415311828?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Shopee', url: '#' }] },
//       { name: 'Áo phông in hình', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1588185908663-85e493e501b1?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Quần jean rách', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Bốt da lộn', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 13,
//     gender: 'female',
//     context: 'casual',
//     style: 'basic',
//     season: 'summer',
//     color: 'white',
//     mainImage: 'https://images.unsplash.com/photo-1590248434230-07132a22c5a2?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-in-white-dress-standing-on-brown-sand-during-daytime-07132a22c5a2',
//     description: 'Váy maxi đi biển',
//     longDescription: 'Nhẹ nhàng và thoáng mát, hoàn hảo cho một ngày đi biển hoặc kỳ nghỉ.',
//     aiHint: 'woman beach dress',
//     items: [
//       { name: 'Váy maxi trắng', type: 'Váy', imageUrl: 'https://images.unsplash.com/photo-1590248434230-07132a22c5a2?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }, { store: 'Shopee', url: '#' }] },
//       { name: 'Sandal quai mảnh', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1603487742131-411a791ec30b?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Mũ rơm', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1533514134766-03c27a365f12?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Túi cói', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//    {
//     id: 14,
//     gender: 'male',
//     context: 'casual',
//     style: 'basic',
//     season: 'summer',
//     color: 'earth-tone',
//     mainImage: 'https://images.unsplash.com/photo-1622519369527-3a1396910793?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/a-man-in-a-white-shirt-and-white-shorts-is-walking-on-the-beach-3a1396910793',
//     description: 'Trang phục đi biển cho nam',
//     longDescription: 'Thư giãn và thoải mái cho một ngày đi biển.',
//     aiHint: 'man beach outfit',
//     items: [
//       { name: 'Áo sơ mi linen màu be', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1622519369527-3a1396910793?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Uniqlo', url: '#' }] },
//       { name: 'Quần short trắng', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1603344287447-1f4a9a4e6c64?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Dép xỏ ngón da', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1603487742131-411a791ec30b?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Kính râm phi công', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 15,
//     gender: 'female',
//     context: 'party/date',
//     style: 'elegant',
//     season: 'winter',
//     color: 'vibrant',
//     mainImage: 'https://images.unsplash.com/photo-1603921501867-899e3102f026?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/woman-in-red-long-sleeve-dress-899e3102f026',
//     description: 'Váy nhung cho buổi hẹn hò tối',
//     longDescription: 'Quyến rũ và sang trọng cho một buổi hẹn hò lãng mạn mùa đông.',
//     aiHint: 'woman velvet dress',
//     items: [
//       { name: 'Váy nhung đỏ', type: 'Váy', imageUrl: 'https://images.unsplash.com/photo-1603921501867-899e3102f026?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Zara', url: '#' }] },
//       { name: 'Giày cao gót đen', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1590099033615-be195f8d575c?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Túi clutch bạc', type: 'Phụ kiện', imageUrl: 'https://images.unsplash.com/photo-1566150905458-1bf1f2997d0d?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
//   {
//     id: 16,
//     gender: 'male',
//     context: 'casual',
//     style: 'streetwear',
//     season: 'spring',
//     color: 'white',
//     mainImage: 'https://images.unsplash.com/photo-1559535332-db1c283b3e34?w=400&h=500&fit=crop',
//     imageSourceText: 'Unsplash',
//     imageSourceUrl: 'https://unsplash.com/photos/man-in-blue-denim-jacket-and-black-pants-standing-beside-white-wall-db1c283b3e34',
//     description: 'Phong cách dạo phố đi học',
//     longDescription: 'Thoải mái và phong cách, hoàn hảo cho việc đi học hoặc dạo phố.',
//     aiHint: 'man school streetwear',
//     items: [
//       { name: 'Áo khoác denim', type: 'Áo khoác', imageUrl: 'https://images.unsplash.com/photo-1559535332-db1c283b3e34?w=400&h=500&fit=crop', shoppingLinks: [{ store: 'Lazada', url: '#' }, { store: 'Shopee', url: '#' }] },
//       { name: 'Áo thun trắng', type: 'Áo', imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Quần jogger đen', type: 'Quần', imageUrl: 'https://images.unsplash.com/photo-1513581381398-3f513f5b7565?w=400&h=500&fit=crop', shoppingLinks: [] },
//       { name: 'Giày sneaker cổ điển', type: 'Giày', imageUrl: 'https://images.unsplash.com/photo-1527010154944-f2241763d806?w=400&h=500&fit=crop', shoppingLinks: [] },
//     ],
//   },
// ];

    

    